# Generated by Django 3.1.4 on 2021-01-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhospital', '0002_auto_20210103_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
