# Generated by Django 3.1.4 on 2021-01-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myhospital', '0003_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Username', models.EmailField(max_length=40)),
                ('Password', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Image/profilepic')),
            ],
        ),
    ]
