# Generated by Django 3.1.4 on 2021-01-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hsp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Passwprd',
            new_name='Password',
        ),
    ]
