# Generated by Django 3.1.4 on 2021-01-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_content',
            options={},
        ),
    ]
